/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagementsystem;

/**
 *
 * @author Abuga Aroni
 */
public class Caretaker {
    
private int CaretakerID;
private String Fname;
private    String Lname;
private int PhoneNo;
private String Address;

//constructor
public Caretaker(int CId, String Firstname, String Lastname, int PNo, String CAddress)
{ CaretakerID = CId;
Fname = Firstname;
Lname = Lastname;
PhoneNo = PNo;
Address = CAddress;}   
    
//setters and getters generated by netbeans alt-int function

    public int getCaretakerID() {
        return CaretakerID;
    }

    public void setCaretakerID(int CaretakerID) {
        this.CaretakerID = CaretakerID;
    }

    public String getFname() {
        return Fname;
    }

    public void setFname(String Fname) {
        this.Fname = Fname;
    }

    public String getLname() {
        return Lname;
    }

    public void setLname(String Lname) {
        this.Lname = Lname;
    }

    public int getPhoneNo() {
        return PhoneNo;
    }

    public void setPhoneNo(int PhoneNo) {
        this.PhoneNo = PhoneNo;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }


}
