/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagementsystem;

/**
 *
 * @author Abuga Aroni
 */
public class Client {

//Entity variables
  private int ClientID_No;
  private String Fname;
  private String Lname;
  private int PhoneNo;
    //foreignkey/foreign attribute, not sure how to do that,
  private int GuarantorId_No;

 //constructor
  public Client (int CId, String Firstname, String Lastname, int PNumber, int GId) {
  ClientID_No = CId;
  Fname = Firstname;
  Lname = Lastname;
  PhoneNo = PNumber;
  GuarantorId_No = GId;
    }
 
  //setters and getters generated by netbeans alt-int shortcut
    public int getClientID_No() {
        return ClientID_No;
    }

    public void setClientID_No(int ClientID_No) {
        this.ClientID_No = ClientID_No;
    }

    public String getFname() {
        return Fname;
    }

    public void setFname(String Fname) {
        this.Fname = Fname;
    }

    public String getLname() {
        return Lname;
    }

    public void setLname(String Lname) {
        this.Lname = Lname;
    }

    public int getPhoneNo() {
        return PhoneNo;
    }

    public void setPhoneNo(int PhoneNo) {
        this.PhoneNo = PhoneNo;
    }

    public int getGuarantorId_No() {
        return GuarantorId_No;
    }

    public void setGuarantorId_No(int GuarantorId_No) {
        this.GuarantorId_No = GuarantorId_No;
    }


}
