/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagementsystem;

/**
 *
 * @author Abuga Aroni
 */
public class Contract {
    private int ContractNo;
    private String Start;
    private String End;
    //foreign keys below
    private int ClientID; 
    private int HouseNo;
    
    //constructor
    
public Contract (int CNo, String CStart, String CEnd, int CId, int Hnumber) 
{ ContractNo = CNo;
  Start = CStart;
  End = CEnd;
  ClientID = CId;
  HouseNo = Hnumber;
}

//setters and getters generated by alt-int function

    public int getContractNo() {
        return ContractNo;
    }

    public void setContractNo(int ContractNo) {
        this.ContractNo = ContractNo;
    }

    public String getStart() {
        return Start;
    }

    public void setStart(String Start) {
        this.Start = Start;
    }

    public String getEnd() {
        return End;
    }

    public void setEnd(String End) {
        this.End = End;
    }

    public int getClientID() {
        return ClientID;
    }

    public void setClientID(int ClientID) {
        this.ClientID = ClientID;
    }

    public int getHouseNo() {
        return HouseNo;
    }

    public void setHouseNo(int HouseNo) {
        this.HouseNo = HouseNo;
    }


}
