/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagementsystem;
import java.util.Scanner;

/**
 *
 * @author Abuga Aroni
 */
public class Guarantor {
private int GuarantorID_No;
private String Fname;
private String Lname;
private int PhoneNo;
private String Address;

//constructor
/*public Guarantor(int GId, String Firstname, String Lastname, int PNumber, String GAddress)
{ GuarantorID_No = GId;
 Fname = Firstname;
  Lname = Lastname;
  PhoneNo = PNumber;
  Address = GAddress;
    } */
public Guarantor()
{ GuarantorID_No = 0;
 Fname = null;
  Lname = null;
  PhoneNo = 0;
  Address = null;
    }
//setters and getters generated by netbeands alt-int shortcut

    public int getGuarantorID_No() {
        return GuarantorID_No;
    }

    public void setGuarantorID_No(int GuarantorID_No) {
        this.GuarantorID_No = GuarantorID_No;
    }

    public String getFname() {
        return Fname;
    }

    public void setFname(String Fname) {
        this.Fname = Fname;
    }

    public String getLname() {
        return Lname;
    }

    public void setLname(String Lname) {
        this.Lname = Lname;
    }

    public int getPhoneNo() {
        return PhoneNo;
    }

    public void setPhoneNo(int PhoneNo) {
        this.PhoneNo = PhoneNo;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

public void showGdetails () {
    System.out.println ("These are the details you have input");
    System.out.println("Guarantor ID: " + GuarantorID_No);
    System.out.println("Guarantor name: " + Fname + " " + Lname);
    System.out.println("Phone number: " + PhoneNo);
    System.out.println("Address: " + Address);
    }  
}

