/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagementsystem;
/**
 *
 * @author Abuga Aroni
 */
public class House {
//Entity Variables
  private  int HouseNo;
  private  String Address;
  private  String Type;
  private  int NoOfRooms;
  private  int Toilets;
  
//constructors
   public House (){
   HouseNo = 0;
   Address = null ;
   Type = null;
   NoOfRooms = 0;
   Toilets = 0;
   }
   
//Setter and Getters - generated by netbeans alt-int shortcut
    public int getHouseNo() {
        return HouseNo;
    }

    public void setHouseNo(int HouseNo) {
        this.HouseNo = HouseNo;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

    public int getNoOfRooms() {
        return NoOfRooms;
    }

    public void setNoOfRooms(int NoOfRooms) {
        this.NoOfRooms = NoOfRooms;
    }

    public int getToilets() {
        return Toilets;
    }

    public void setToilets(int Toilets) {
        this.Toilets = Toilets;
    }
    
 //method to show house details for given object
    public void showHdetails () {
    System.out.println ("These are the details you have input");
    System.out.println("House number: " + HouseNo);
    System.out.println("House address: " + Address);
    System.out.println("Type of House: " + Type);
    System.out.println("No of Rooms: " + NoOfRooms);
    System.out.println("No of Toilets: " + Toilets);
    }  
   
   
}
